### ISSUE TITLE
Hostname XMLHttpRequest blocked by CORS policy 

### ISSUE THREAD

**Issue by glynhudson** [OpenEVSE/ESP32_WiFi_V3.x#24]
Using hostname lookup in a desktop browser e.g http://openevse.local results in the following errors. These errors result in some parameters not being displayed e.g max current

`Access to XMLHttpRequest at 'http://192.168.86.20/r?json=1&rapi=$GH' from origin 'http://openevse.local' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

## Using hostname access:

![Screenshot 2019-09-22 at 19 06 09](https://user-images.githubusercontent.com/758844/65392396-74f60f00-dd6c-11e9-9f92-229308d7aad8.png)

## Using direct IP address (no errors):

![Screenshot 2019-09-22 at 19 06 20](https://user-images.githubusercontent.com/758844/65392403-8212fe00-dd6c-11e9-835e-4242f78dc30c.png)

**Comment by jeremypoulter** [comment]
This will be also related to setting headers not working jeremypoulter/ArduinoMongoose#3

**Comment by jeremypoulter** [comment]
Fixed with jeremypoulter/ArduinoMongoose#3

**Comment by glynhudson** [comment]
I'm still experiencing the same issue when using hostname lookup after updating 

![Screenshot 2019-10-01 at 01 24 52](https://user-images.githubusercontent.com/758844/65925868-60f48200-e3ea-11e9-80bb-d9d78ef558ab.png)

**Comment by jeremypoulter** [comment]
Are you using the latest ArduinoMongoose library? Probably a good time to register it properly...

**Comment by jeremypoulter** [comment]
Just pushed an update to force the latest version

**Comment by glynhudson** [comment]
Yes, I'm pretty sure I'm running the latest version. Before compiling I ran `pio lib install https://github.com/jeremypoulter/ArduinoMongoose.git`. Just tested again with same result

**Comment by glynhudson** [comment]
Ok, fixed now using V0.0.3 of Arduino Mongoose
